name: Exit Code Demo

on: workflow_dispatch

permissions:
  contents: write

jobs:
  check-exit-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Datestamp
        run: python ./datestamp.py
      - name: Check for changes
        id: run_command
        run: |
          git diff --quiet && git diff --cached --quiet
          echo "HAS_CHANGES=$?" >> "$GITHUB_OUTPUT"
        continue-on-error: true # nonzero output is an option here, not a terminating error
      # Nothing to do
      - name: Diff empty
        if: ${{ steps.run_command.outputs.HAS_CHANGES == '0' }}
        run: echo "exit code 0, conclusion ${{ steps.run_command.conclusion }}, code ${{steps.run_command.outputs.HAS_CHANGES}}"
      # Commit changelog/json
      - name: Diff not empty
        if: ${{ steps.run_command.outputs.HAS_CHANGES != '0' }}
        run: |
          echo "exit code non-0, conclusion ${{ steps.run_command.conclusion }}, code ${{steps.run_command.outputs.HAS_CHANGES}}"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Release version ${{env.MOD_VERSION}}"
          git tag v${{env.MOD_VERSION}}
          git push origin v${{env.MOD_VERSION}} --dry-run

