name: Exit Code Demo

on: workflow_dispatch

jobs:
  check-exit-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Datestamp
        run: python ./datestamp.py
      - name: Check for changes
        id: run_command
        run: |
          git diff --quiet && git diff --cached --quiet
          echo "EXIT_CODE=$?" >> "$GITHUB_ENV"
        continue-on-error: true # nonzero output is an option here, not a terminating error
      - name: unquiet check
        run: git status --porcelain
      - name: Diff empty
        if: ${{ steps.run_command.outputs.EXIT_CODE == '0' }}
        run: echo "exit code 0, conclusion ${{ steps.run_command.conclusion }}, code ${{steps.run_command.outputs.EXIT_CODE}}"

      - name: Diff not empty
        if: ${{ steps.run_command.outputs.EXIT_CODE != '0' }}
        run: echo "exit code non-0, conclusion ${{ steps.run_command.conclusion }}, code ${{steps.run_command.outputs.EXIT_CODE}}"
