name: Exit Code Demo

on: workflow_dispatch

permissions:
  contents: write

jobs:
  datestamp:
    name: "Datestamp & version"
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.run_command.outputs.HAS_CHANGES }} # '0' or non-zero
      mod_name: ${{ env.MOD_NAME }} # not always the same as the repo!
      mod_version: ${{ env.MOD_VERSION }}
      mod_zip_path: ${{ env.MOD_ZIP_PATH }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.head_ref || github.ref_name }}
      - name: Datestamp
        run: python ./datestamp.py
      - name: Check for changes
        id: run_command
        run: |
          git diff --quiet && git diff --cached --quiet
          echo "HAS_CHANGES=$?" >> "$GITHUB_OUTPUT"
        continue-on-error: true # nonzero output is an option here, not a terminating error
      # Nothing to do
      - name: Diff empty
        if: ${{ steps.run_command.outputs.HAS_CHANGES == '0' }}
        run: echo "exit code 0, code ${{ steps.run_command.outputs.HAS_CHANGES }}"
      # Commit changelog/json
      - name: Diff not empty
        if: ${{ steps.run_command.outputs.HAS_CHANGES != '0' }}
        run: |
          echo "exit code non-0, code ${{ steps.run_command.outputs.HAS_CHANGES }}"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Release version ${{ env.MOD_VERSION }}"
          git tag v${{ env.MOD_VERSION }}
          git push origin v${{ env.MOD_VERSION }} --dry-run

